spring.application.name=localbands
logging.level.com.concertn.localbands=DEBUG

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/bands_dev
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.6-luna
spring.ai.openai.chat.reasoning-effort=low
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.com.openai=DEBUG
logging.level.okhttp3=DEBUG
spring.ai.openai.chat.options.timeout=120s
#token limiter?

google.api.key=${MAPS_PLAT_API_KEY}
